# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: DalamudPluginCL
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    
jobs:
  build:

    runs-on: windows-latest

    env:
      DALAMUD_HOME: C:\tmp\dalamud
    steps:

    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Download Dalamud Latest
      run: |
        Invoke-WebRequest -Uri https://raw.githubusercontent.com/ottercorp/dalamud-distrib/main/stg/latest.zip -OutFile latest.zip
        Expand-Archive -Force latest.zip ${{ env.DALAMUD_HOME }}
    - name: Restore dependencies
      run: dotnet restore
      
    - name: publish
      run: dotnet publish

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: src\bin\Release\GoldSaucer\latest.zip
        body: ${{ github.events.commits[0].message }}
